SCRIPT_DIR=$(cd $(dirname $0); pwd)
SRC_NEOVIM_DIR=$SCRIPT_DIR/../nvim
SRC_NEOVIM_INIT_FILE=$SRC_NEOVIM_DIR/init.vim
SRC_NEOVIM_CONFIG_DIR=$SRC_NEOVIM_DIR/_config
SRC_COC_CONFIG_FILE=$SRC_NEOVIM_DIR/coc-settings.json
if [ -n "$XDG_CONFIG_HOME" ]; then
  DIST_NEOVIM_DIR=$XDG_CONFIG_HOME/nvim
else
  DIST_NEOVIM_DIR=$HOME/.config/nvim
fi
DIST_NEOVIM_INIT_FILE=$DIST_NEOVIM_DIR/init.vim
DIST_NEOVIM_CONFIG_DIR=$DIST_NEOVIM_DIR/_config
DIST_COC_CONFIG_FILE=$DIST_NEOVIM_DIR/coc-settings.json

mkdir -p $DIST_NEOVIM_DIR
ln -s $SRC_NEOVIM_INIT_FILE $DIST_NEOVIM_INIT_FILE
ln -s $SRC_NEOVIM_CONFIG_DIR $DIST_NEOVIM_CONFIG_DIR
ln -s $SRC_COC_CONFIG_FILE $DIST_COC_CONFIG_FILE

